### ISSUE TITLE
"rom size is too smal"

### ISSUE THREAD

**Issue by thar0x29a** [pelrun/Dispel#4]
Im not sure how this check is usefull. Some smal demos just lay beyond the assumed size

**Comment by pelrun** [comment]
ROMs are just a raw binary dump, so there's no good way of ensuring you didn't pass in a completely invalid file. I think I was assuming that a rom is always going to be at least one bank big; I was only thinking of actual games and not demos.

Got an explicit example?

**Comment by thar0x29a** [comment]
Well I came up with this because I sniff behind what the bass macro interpreter is doing. For starter I was using https://github.com/PeterLemon/SNES/tree/master/HelloWorld/ 
I would prefer to having at least a flag that is switching the size check off. Many small tech demos for special chips dont rlly exceed this size anyway. But they are the interesting stuff to disassemble ^^

**Comment by pelrun** [comment]
As the SNES requires some specific data at the end of the first bank, the ROM has to be at least that large to work at all. Where I've gone wrong is that a LoROM bank is 32k, half the limit I set.

**Comment by pelrun** [comment]
Fixed the size check, and made it issue a warning rather than terminate.
